### ISSUE TITLE
Could not find 'jekyll' (>= 0.a) among 16 total gem(s)

### ISSUE THREAD

**Issue by iamquan** [willianjusten/cards-jekyll-template#17]
Hi,

I followed these instruction on README:

```
gem install jekyll
sudo npm install
sudo npm install -g gulp gulp-cli
```

then I ran ```sudo gulp``` to compile the assets, it showed the error:

```
[16:48:58] Using gulpfile ~/workspace/cards-jekyll-template/gulpfile.js
[16:48:58] Starting 'js'...
[16:48:58] Starting 'stylus'...
[16:48:58] Finished 'stylus' after 17 ms
[16:48:58] Starting 'jekyll-build'...
[16:48:58] Starting 'watch'...
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'jekyll' (>= 0.a) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/ubuntu/.gem/ruby/2.3.0:/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/jekyll:22:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[16:49:00] Finished 'watch' after 2.09 s
[16:49:00] 'jekyll-build' errored after 2.16 s
```
My node version is 6.3.1

**Comment by iamquan** [comment]
It turns out if you do ```sudo``` command with ```npm install```, ```npm install -g gulp gulp-cli```, ```gulp```, you also have to run ```sudo``` with ```gem install jekyll```. My mistake.
