### ISSUE TITLE
Error: spawn jekyll ENOENT

### ISSUE THREAD

**Issue by sonalkr132** [willianjusten/cards-jekyll-template#20]
Steps I followed to setup:
```sh
$ node -v
v7.4.0
$ sudo npm install
$ sudo npm install -g gulp gulp-cli
$ sudo gulp
[21:43:39] Starting 'js'...
[21:43:39] Starting 'stylus'...
[21:43:39] Finished 'stylus' after 9.68 ms
[21:43:39] Starting 'jekyll-build'...
[21:43:39] Starting 'watch'...
[21:43:41] Finished 'watch' after 1.48 s
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any help would be really appreciated :raising_hand_man: I am using Fedora 24.

**Comment by willianjusten** [comment]
Have you installed `jekyll` first? If not, run this line before:

`sudo gem install jekyll`

**Comment by sonalkr132** [comment]
> Have you installed jekyll first? 

Yes. Of course :sweat_smile: I am using `jekyll 3.4.0`

**Comment by willianjusten** [comment]
Hum...try to run `gulp` without `sudo`.

**Comment by sonalkr132** [comment]
It worked :tada: Thanks @willianjusten :1st_place_medal:
