### ISSUE TITLE
Error: Cannot find module 'minimatch' after `sudo gulp`

### ISSUE THREAD

**Issue by mohataher** [willianjusten/cards-jekyll-template#31]
When running 
```
sudo gulp
```

An error is thrown. No changes were done to the repo after it was cloned.
```
 user__$ sudo gulp
module.js:529
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
admins-MBP:cards-jekyll-template motaher$ 

```

What's happening?

**Comment by willianjusten** [comment]
Hum...try to run without `sudo`. Actually, we shouldn't use `sudo` to Node stuff. I found out that it's wrong in the Documentation...I'll fix there...

**Comment by mohataher** [comment]
Hi Willian, thanks for responding. It seems like I had an issue with Node.JS installation. I cloned the repo again and tried to run it locally using the updated code. The template loads on `localhost:3000` with no CSS or formatting. Just plain text with an error on the console 

```
main.css: Failed to load resource: the server responded with a status of 404 (Not Found)
main.js: Failed to load resource: the server responded with a status of 404 (Not Found)
main.css: Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by willianjusten** [comment]
Please check your `_config.yml` if it has your correct `baseurl`.

**Comment by mohataher** [comment]
Correct guess. Thanks for your time.
