### ISSUE TITLE
The Header is not changing

### ISSUE THREAD

**Issue by tip4programs** [willianjusten/cards-jekyll-template#35]
The website header always shows **</>  Anon Developer** or **</> AD**(for mobile site). changed header of the site by editing the file /src/style/_header .style like `this`
```
			transition all .4s
			content '</> TP'
			+above(cut)
				content '</> Tip4programs'
```
But the change is not affecting on the website. What is the reason behind this? I have committed this change on both gh-pages and master branch😧.

**Comment by willianjusten** [comment]
Did you run `gulp -p` after the changes? You need to compile, because those `stylus` files will compile to the real `css` used in your site.

**Comment by mstuttgart** [comment]
I find this error after run `gulp -p`

```
[21:29:43] Using gulpfile ~/Workspace/mstuttgart.github.io/gulpfile.js
[21:29:43] Starting 'js'...
[21:29:43] Starting 'stylus'...
[21:29:43] Finished 'stylus' after 3.57 ms
[21:29:43] Starting 'jekyll-build'...
[21:29:43] Starting 'watch'...
[21:29:44] Finished 'watch' after 361 ms
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ghost** [comment]
I modified the header and also `gulp -p`, but after that the website first appeared my name then returned to </> Anon Developer, what's going on?
