### ISSUE TITLE
`gulp` command throwing error

### ISSUE THREAD

**Issue by nikitahl** [willianjusten/cards-jekyll-template#50]
After following instructions in README.md:

- Install [NodeJS](https://nodejs.org/) (remember to use the latest version)
- Run `npm install`
- Run `npm install -g gulp gulp-cli`
- Run `gulp`

Running `gulp` command throws an error:
```
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/nikitahlopovs/Documents/html/cards-jekyll-template/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/nikitahlopovs/Documents/html/cards-jekyll-template/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/nikitahlopovs/Documents/html/cards-jekyll-template/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
```
Possibly need to update packages or config. Please advise. Thank you.

**Comment by willianjusten** [comment]
It's probably due to `gulp` version, check the version that's installed and the version that you're using. This project is not maintained anymore, so I can't help too much because I don't have much time =/
